var hierarchy =
[
    [ "LokalestyringWS.Models.AllBookingsView", "class_lokalestyring_w_s_1_1_models_1_1_all_bookings_view.html", null ],
    [ "LokalestyringUWP.Models.AllBookingsView", "class_lokalestyring_u_w_p_1_1_models_1_1_all_bookings_view.html", null ],
    [ "ApiController", null, [
      [ "LokalestyringWS.Controllers.AllBookingsViewsController", "class_lokalestyring_w_s_1_1_controllers_1_1_all_bookings_views_controller.html", null ],
      [ "LokalestyringWS.Controllers.BookingsController", "class_lokalestyring_w_s_1_1_controllers_1_1_bookings_controller.html", null ],
      [ "LokalestyringWS.Controllers.BuildingsController", "class_lokalestyring_w_s_1_1_controllers_1_1_buildings_controller.html", null ],
      [ "LokalestyringWS.Controllers.LocationsController", "class_lokalestyring_w_s_1_1_controllers_1_1_locations_controller.html", null ],
      [ "LokalestyringWS.Controllers.RoomsController", "class_lokalestyring_w_s_1_1_controllers_1_1_rooms_controller.html", null ],
      [ "LokalestyringWS.Controllers.RoomsViewsController", "class_lokalestyring_w_s_1_1_controllers_1_1_rooms_views_controller.html", null ],
      [ "LokalestyringWS.Controllers.RoomtypesController", "class_lokalestyring_w_s_1_1_controllers_1_1_roomtypes_controller.html", null ],
      [ "LokalestyringWS.Controllers.TavleBookingsController", "class_lokalestyring_w_s_1_1_controllers_1_1_tavle_bookings_controller.html", null ],
      [ "LokalestyringWS.Controllers.UsersController", "class_lokalestyring_w_s_1_1_controllers_1_1_users_controller.html", null ],
      [ "LokalestyringWS.Controllers.ValuesController", "class_lokalestyring_w_s_1_1_controllers_1_1_values_controller.html", null ]
    ] ],
    [ "Application", null, [
      [ "LokalestyringUWP.App", "class_lokalestyring_u_w_p_1_1_app.html", null ],
      [ "UnitTesterForUWP.App", "class_unit_tester_for_u_w_p_1_1_app.html", null ],
      [ "UnitTesterUWP.App", "class_unit_tester_u_w_p_1_1_app.html", null ]
    ] ],
    [ "AreaRegistration", null, [
      [ "LokalestyringWS.Areas.HelpPage.HelpPageAreaRegistration", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_help_page_area_registration.html", null ]
    ] ],
    [ "Attribute", null, [
      [ "LokalestyringUWP.Annotations.AspChildControlTypeAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_child_control_type_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspDataFieldAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_data_field_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspDataFieldsAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_data_fields_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMethodPropertyAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_method_property_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcActionAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_action_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcActionSelectorAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_action_selector_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcAreaAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_area_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcAreaMasterLocationFormatAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_area_master_location_format_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcAreaPartialViewLocationFormatAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_area_partial_view_location_format_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcAreaViewLocationFormatAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_area_view_location_format_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcControllerAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_controller_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcDisplayTemplateAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_display_template_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcEditorTemplateAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_editor_template_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcMasterAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_master_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcMasterLocationFormatAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_master_location_format_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcModelTypeAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_model_type_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcPartialViewAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_partial_view_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcPartialViewLocationFormatAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_partial_view_location_format_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcSuppressViewErrorAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_suppress_view_error_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcTemplateAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_template_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcViewAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_view_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcViewComponentAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_view_component_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcViewComponentViewAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_view_component_view_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspMvcViewLocationFormatAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_mvc_view_location_format_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspRequiredAttributeAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_required_attribute_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AspTypePropertyAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_asp_type_property_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AssertionConditionAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_assertion_condition_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.AssertionMethodAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_assertion_method_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.BaseTypeRequiredAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_base_type_required_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.CanBeNullAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_can_be_null_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.CannotApplyEqualityOperatorAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_cannot_apply_equality_operator_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.CollectionAccessAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_collection_access_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.ContractAnnotationAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_contract_annotation_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.HtmlAttributeValueAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_html_attribute_value_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.HtmlElementAttributesAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_html_element_attributes_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.InstantHandleAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_instant_handle_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.InvokerParameterNameAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_invoker_parameter_name_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.ItemCanBeNullAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_item_can_be_null_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.ItemNotNullAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_item_not_null_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.LinqTunnelAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_linq_tunnel_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.LocalizationRequiredAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_localization_required_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.MacroAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_macro_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.MeansImplicitUseAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_means_implicit_use_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.MustUseReturnValueAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_must_use_return_value_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.NoEnumerationAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_no_enumeration_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.NoReorderAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_no_reorder_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.NotifyPropertyChangedInvocatorAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_notify_property_changed_invocator_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.NotNullAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_not_null_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.PathReferenceAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_path_reference_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.ProvidesContextAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_provides_context_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.PublicAPIAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_public_a_p_i_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.PureAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_pure_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorDirectiveAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_directive_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorHelperCommonAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_helper_common_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorImportNamespaceAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_import_namespace_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorInjectionAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_injection_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorLayoutAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_layout_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorPageBaseTypeAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_page_base_type_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorSectionAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_section_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorWriteLiteralMethodAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_write_literal_method_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorWriteMethodAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_write_method_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RazorWriteMethodParameterAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_razor_write_method_parameter_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.RegexPatternAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_regex_pattern_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.SourceTemplateAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_source_template_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.StringFormatMethodAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_string_format_method_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.TerminatesProgramAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_terminates_program_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.UsedImplicitlyAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_used_implicitly_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.ValueProviderAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_value_provider_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.XamlItemBindingOfItemsControlAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_xaml_item_binding_of_items_control_attribute.html", null ],
      [ "LokalestyringUWP.Annotations.XamlItemsControlAttribute", "class_lokalestyring_u_w_p_1_1_annotations_1_1_xaml_items_control_attribute.html", null ],
      [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.ModelNameAttribute", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_model_name_attribute.html", null ]
    ] ],
    [ "LokalestyringWS.Models.Booking", "class_lokalestyring_w_s_1_1_models_1_1_booking.html", null ],
    [ "LokalestyringUWP.Models.Booking", "class_lokalestyring_u_w_p_1_1_models_1_1_booking.html", null ],
    [ "LokalestyringUWP.Models.Singletons.BookingCatalogSingleton", "class_lokalestyring_u_w_p_1_1_models_1_1_singletons_1_1_booking_catalog_singleton.html", null ],
    [ "UnitTester.Tests.BookTest", "class_unit_tester_1_1_tests_1_1_book_test.html", null ],
    [ "LokalestyringWS.Models.Building", "class_lokalestyring_w_s_1_1_models_1_1_building.html", null ],
    [ "LokalestyringUWP.Models.Building", "class_lokalestyring_u_w_p_1_1_models_1_1_building.html", null ],
    [ "LokalestyringWS.BundleConfig", "class_lokalestyring_w_s_1_1_bundle_config.html", null ],
    [ "LokalestyringUWP.ViewModel.BurgerMenuVM", "class_lokalestyring_u_w_p_1_1_view_model_1_1_burger_menu_v_m.html", null ],
    [ "Controller", null, [
      [ "LokalestyringWS.Areas.HelpPage.Controllers.HelpController", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_controllers_1_1_help_controller.html", null ],
      [ "LokalestyringWS.Controllers.HomeController", "class_lokalestyring_w_s_1_1_controllers_1_1_home_controller.html", null ]
    ] ],
    [ "LokalestyringUWP.ViewModel.CreateAccountVM", "class_lokalestyring_u_w_p_1_1_view_model_1_1_create_account_v_m.html", null ],
    [ "DbContext", null, [
      [ "LokalestyringWS.Models.LokalestyringDBContext", "class_lokalestyring_w_s_1_1_models_1_1_lokalestyring_d_b_context.html", null ]
    ] ],
    [ "LokalestyringUWP.Handler.DialogHandler", "class_lokalestyring_u_w_p_1_1_handler_1_1_dialog_handler.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.EnumValueDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_enum_value_description.html", null ],
    [ "LokalestyringWS.FilterConfig", "class_lokalestyring_w_s_1_1_filter_config.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.Models.HelpPageApiModel", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_models_1_1_help_page_api_model.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.HelpPageSampleGenerator", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_help_page_sample_generator.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.HelpPageSampleKey", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_help_page_sample_key.html", null ],
    [ "HttpApplication", null, [
      [ "LokalestyringWS.WebApiApplication", "class_lokalestyring_w_s_1_1_web_api_application.html", null ]
    ] ],
    [ "ICommand", null, [
      [ "LokalestyringUWP.Common.RelayCommand", "class_lokalestyring_u_w_p_1_1_common_1_1_relay_command.html", null ]
    ] ],
    [ "IComponentConnector", null, [
      [ "LokalestyringUWP.View.PageAccountSettings", "class_lokalestyring_u_w_p_1_1_view_1_1_page_account_settings.html", null ],
      [ "LokalestyringUWP.View.PageBookRooms", "class_lokalestyring_u_w_p_1_1_view_1_1_page_book_rooms.html", null ],
      [ "LokalestyringUWP.View.PageCreateAccount", "class_lokalestyring_u_w_p_1_1_view_1_1_page_create_account.html", null ],
      [ "LokalestyringUWP.View.PageLocations", "class_lokalestyring_u_w_p_1_1_view_1_1_page_locations.html", null ],
      [ "LokalestyringUWP.View.PageLogin", "class_lokalestyring_u_w_p_1_1_view_1_1_page_login.html", null ],
      [ "LokalestyringUWP.View.PageTeacherControlPanel", "class_lokalestyring_u_w_p_1_1_view_1_1_page_teacher_control_panel.html", null ],
      [ "LokalestyringUWP.View.PageUserBookings", "class_lokalestyring_u_w_p_1_1_view_1_1_page_user_bookings.html", null ]
    ] ],
    [ "IComponentConnector2", null, [
      [ "LokalestyringUWP.View.PageAccountSettings", "class_lokalestyring_u_w_p_1_1_view_1_1_page_account_settings.html", null ],
      [ "LokalestyringUWP.View.PageBookRooms", "class_lokalestyring_u_w_p_1_1_view_1_1_page_book_rooms.html", null ],
      [ "LokalestyringUWP.View.PageCreateAccount", "class_lokalestyring_u_w_p_1_1_view_1_1_page_create_account.html", null ],
      [ "LokalestyringUWP.View.PageLocations", "class_lokalestyring_u_w_p_1_1_view_1_1_page_locations.html", null ],
      [ "LokalestyringUWP.View.PageLogin", "class_lokalestyring_u_w_p_1_1_view_1_1_page_login.html", null ],
      [ "LokalestyringUWP.View.PageTeacherControlPanel", "class_lokalestyring_u_w_p_1_1_view_1_1_page_teacher_control_panel.html", null ],
      [ "LokalestyringUWP.View.PageUserBookings", "class_lokalestyring_u_w_p_1_1_view_1_1_page_user_bookings.html", null ]
    ] ],
    [ "IDocumentationProvider", null, [
      [ "LokalestyringWS.Areas.HelpPage.XmlDocumentationProvider", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_xml_documentation_provider.html", null ]
    ] ],
    [ "LokalestyringWS.Areas.HelpPage.ImageSample", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_image_sample.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.IModelDocumentationProvider", "interface_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_i_model_documentation_provider.html", [
      [ "LokalestyringWS.Areas.HelpPage.XmlDocumentationProvider", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_xml_documentation_provider.html", null ]
    ] ],
    [ "INotifyPropertyChanged", null, [
      [ "LokalestyringUWP.Handler.UserBookingHandler", "class_lokalestyring_u_w_p_1_1_handler_1_1_user_booking_handler.html", null ],
      [ "LokalestyringUWP.Models.Singletons.AllBookingsViewCatalogSingleton", "class_lokalestyring_u_w_p_1_1_models_1_1_singletons_1_1_all_bookings_view_catalog_singleton.html", null ],
      [ "LokalestyringUWP.ViewModel.AccountSettingsVM", "class_lokalestyring_u_w_p_1_1_view_model_1_1_account_settings_v_m.html", null ],
      [ "LokalestyringUWP.ViewModel.BookRoomsVM", "class_lokalestyring_u_w_p_1_1_view_model_1_1_book_rooms_v_m.html", null ],
      [ "LokalestyringUWP.ViewModel.TeacherControlPanelVM", "class_lokalestyring_u_w_p_1_1_view_model_1_1_teacher_control_panel_v_m.html", null ],
      [ "LokalestyringUWP.ViewModel.UserBookingsVM", "class_lokalestyring_u_w_p_1_1_view_model_1_1_user_bookings_v_m.html", null ]
    ] ],
    [ "LokalestyringWS.Areas.HelpPage.InvalidSample", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_invalid_sample.html", null ],
    [ "IValueConverter", null, [
      [ "LokalestyringUWP.Handler.DateFormatConverter", "class_lokalestyring_u_w_p_1_1_handler_1_1_date_format_converter.html", null ]
    ] ],
    [ "IXamlMetadataProvider", null, [
      [ "LokalestyringUWP.LokalestyringUWP_XamlTypeInfo.XamlMetaDataProvider", "class_lokalestyring_u_w_p_1_1_lokalestyring_u_w_p___xaml_type_info_1_1_xaml_meta_data_provider.html", null ]
    ] ],
    [ "LokalestyringWS.Models.Location", "class_lokalestyring_w_s_1_1_models_1_1_location.html", null ],
    [ "LokalestyringUWP.Models.Location", "class_lokalestyring_u_w_p_1_1_models_1_1_location.html", null ],
    [ "LokalestyringUWP.Models.Singletons.LocationSingleton", "class_lokalestyring_u_w_p_1_1_models_1_1_singletons_1_1_location_singleton.html", null ],
    [ "LokalestyringUWP.ViewModel.LocationsVM", "class_lokalestyring_u_w_p_1_1_view_model_1_1_locations_v_m.html", null ],
    [ "UnitTester.Tests.LocationTest", "class_unit_tester_1_1_tests_1_1_location_test.html", null ],
    [ "UnitTester.Tests.LoginTest", "class_unit_tester_1_1_tests_1_1_login_test.html", null ],
    [ "LokalestyringUWP.ViewModel.LoginVM", "class_lokalestyring_u_w_p_1_1_view_model_1_1_login_v_m.html", null ],
    [ "LokalestyringUWP.Service.MailService", "class_lokalestyring_u_w_p_1_1_service_1_1_mail_service.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.ModelDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_model_description.html", [
      [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.CollectionModelDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_collection_model_description.html", null ],
      [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.ComplexTypeModelDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_complex_type_model_description.html", null ],
      [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.EnumTypeModelDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_enum_type_model_description.html", null ],
      [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.KeyValuePairModelDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_key_value_pair_model_description.html", [
        [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.DictionaryModelDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_dictionary_model_description.html", null ]
      ] ],
      [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.SimpleTypeModelDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_simple_type_model_description.html", null ]
    ] ],
    [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.ModelDescriptionGenerator", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_model_description_generator.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.ObjectGenerator", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_object_generator.html", null ],
    [ "Page", null, [
      [ "LokalestyringUWP.View.PageAccountSettings", "class_lokalestyring_u_w_p_1_1_view_1_1_page_account_settings.html", null ],
      [ "LokalestyringUWP.View.PageBookRooms", "class_lokalestyring_u_w_p_1_1_view_1_1_page_book_rooms.html", null ],
      [ "LokalestyringUWP.View.PageCreateAccount", "class_lokalestyring_u_w_p_1_1_view_1_1_page_create_account.html", null ],
      [ "LokalestyringUWP.View.PageLocations", "class_lokalestyring_u_w_p_1_1_view_1_1_page_locations.html", null ],
      [ "LokalestyringUWP.View.PageLogin", "class_lokalestyring_u_w_p_1_1_view_1_1_page_login.html", null ],
      [ "LokalestyringUWP.View.PageTeacherControlPanel", "class_lokalestyring_u_w_p_1_1_view_1_1_page_teacher_control_panel.html", null ],
      [ "LokalestyringUWP.View.PageUserBookings", "class_lokalestyring_u_w_p_1_1_view_1_1_page_user_bookings.html", null ]
    ] ],
    [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.ParameterAnnotation", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_parameter_annotation.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.ModelDescriptions.ParameterDescription", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_parameter_description.html", null ],
    [ "LokalestyringUWP.Service.PersistancyService", "class_lokalestyring_u_w_p_1_1_service_1_1_persistancy_service.html", null ],
    [ "LokalestyringWS.Models.Room", "class_lokalestyring_w_s_1_1_models_1_1_room.html", null ],
    [ "LokalestyringUWP.Models.Room", "class_lokalestyring_u_w_p_1_1_models_1_1_room.html", null ],
    [ "LokalestyringUWP.Handler.RoomHandler", "class_lokalestyring_u_w_p_1_1_handler_1_1_room_handler.html", null ],
    [ "LokalestyringWS.Models.RoomsView", "class_lokalestyring_w_s_1_1_models_1_1_rooms_view.html", null ],
    [ "LokalestyringUWP.Models.RoomsView", "class_lokalestyring_u_w_p_1_1_models_1_1_rooms_view.html", null ],
    [ "LokalestyringUWP.Models.Singletons.RoomsViewCatalogSingleton", "class_lokalestyring_u_w_p_1_1_models_1_1_singletons_1_1_rooms_view_catalog_singleton.html", null ],
    [ "LokalestyringUWP.Models.Roomtype", "class_lokalestyring_u_w_p_1_1_models_1_1_roomtype.html", null ],
    [ "LokalestyringWS.Models.Roomtype", "class_lokalestyring_w_s_1_1_models_1_1_roomtype.html", null ],
    [ "LokalestyringWS.RouteConfig", "class_lokalestyring_w_s_1_1_route_config.html", null ],
    [ "LokalestyringWS.Models.TavleBooking", "class_lokalestyring_w_s_1_1_models_1_1_tavle_booking.html", null ],
    [ "LokalestyringUWP.Models.TavleBooking", "class_lokalestyring_u_w_p_1_1_models_1_1_tavle_booking.html", null ],
    [ "LokalestyringUWP.Models.Singletons.TavleBookingCatalogSingleton", "class_lokalestyring_u_w_p_1_1_models_1_1_singletons_1_1_tavle_booking_catalog_singleton.html", null ],
    [ "LokalestyringUWP.Handler.TeacherPanelBookingHandler", "class_lokalestyring_u_w_p_1_1_handler_1_1_teacher_panel_booking_handler.html", null ],
    [ "LokalestyringWS.Areas.HelpPage.TextSample", "class_lokalestyring_w_s_1_1_areas_1_1_help_page_1_1_text_sample.html", null ],
    [ "UnitTesterForUWP.UnitTest1", "class_unit_tester_for_u_w_p_1_1_unit_test1.html", null ],
    [ "UnitTesterUWP.Tests.UnitTestLogin", "class_unit_tester_u_w_p_1_1_tests_1_1_unit_test_login.html", null ],
    [ "LokalestyringUWP.Models.User", "class_lokalestyring_u_w_p_1_1_models_1_1_user.html", null ],
    [ "LokalestyringWS.Models.User", "class_lokalestyring_w_s_1_1_models_1_1_user.html", null ],
    [ "LokalestyringUWP.Models.Singletons.UserCatalogSingleton", "class_lokalestyring_u_w_p_1_1_models_1_1_singletons_1_1_user_catalog_singleton.html", null ],
    [ "UserControl", null, [
      [ "LokalestyringUWP.Include.BurgerMenu", "class_lokalestyring_u_w_p_1_1_include_1_1_burger_menu.html", null ]
    ] ],
    [ "LokalestyringUWP.Handler.UserHandler", "class_lokalestyring_u_w_p_1_1_handler_1_1_user_handler.html", null ]
];